@hostname = localhost
@port = 3000

GET http://{{hostname}}:{{port}}/

###

# @name postSession
POST http://{{hostname}}:{{port}}/api/session
Content-Type: application/json

{
    "title": "my estimation"
}

###

@sessionId = {{postSession.response.body.$.id}}

###

GET http://{{hostname}}:{{port}}/api/session/{{sessionId}}
